export const fetchDashboardStats = () => ({
  totalUsers: 720,
  totalDonations: 3800,
  pendingDonations: 110,
  availableFood: '1,450 kg',
  feedbackCount: 245,
  reportsCount: 48,
  recentActivities: [
    { id: 1, text: '🍽️ Mezban Restaurant donated 30 kg Chicken Dum Biriyani', time: '2 min ago' },
    { id: 2, text: '🚚 Agrabad Food Bank picked up 20 kg Mutton Teheri', time: '15 min ago' },
    { id: 3, text: '🏠 New orphanage request from Halishahar', time: '42 min ago' },
    { id: 4, text: '✅ 12 donations approved by admin', time: '1 hour ago' },
    { id: 5, text: '📦 Inventory updated: Chicken Fried Rice & Pasta stock increased', time: '2 hours ago' },
    { id: 6, text: '⭐ Suzana gave 5-star feedback to Mezban', time: '3 hours ago' },
  ]
});

export const fetchUsers = () => [
  { id: 1, name: 'Mezban Restaurant', email: 'mezban@rest.com', role: 'Restaurant', location: 'Agrabad, Ctg', status: 'Active' },
  { id: 2, name: 'Chittagong Food Bank', email: 'ctgfood@ngo.org', role: 'NGO', location: 'Nasirabad, Ctg', status: 'Verified' },
  { id: 3, name: 'Bismillah Restaurant', email: 'bismillah@rest.com', role: 'Restaurant', location: 'GEC, Ctg', status: 'Active' },
  { id: 4, name: 'Panshi Restaurant', email: 'panshi@rest.com', role: 'Restaurant', location: 'Bahaddarhat, Ctg', status: 'Active' },
  { id: 5, name: 'Alibaba Restaurant', email: 'alibaba@rest.com', role: 'Restaurant', location: 'Kazir Deuri, Ctg', status: 'Pending' },
  { id: 6, name: 'Kasturi Garden', email: 'kasturi@rest.com', role: 'Restaurant', location: 'Khulshi, Ctg', status: 'Active' },
  { id: 7, name: 'Handi Restaurant', email: 'handi@rest.com', role: 'Restaurant', location: 'Oxygen, Ctg', status: 'Verified' },
  { id: 8, name: 'The Peninsula', email: 'peninsula@rest.com', role: 'Restaurant', location: 'Ctg Club, Ctg', status: 'Active' },
  { id: 9, name: 'Bonanza Restaurant', email: 'bonanza@rest.com', role: 'Restaurant', location: 'Pahartali, Ctg', status: 'Suspended' },
  { id: 10, name: 'Green Hill NGO', email: 'green@ngo.org', role: 'NGO', location: 'Khulshi, Ctg', status: 'Verified' },
  { id: 11, name: 'Suzana Akhter', email: 'suzana@vol.com', role: 'Volunteer', location: 'Agrabad, Ctg', status: 'Active' },
  { id: 12, name: 'Ibthesham Chowdhury', email: 'ibthesham@vol.com', role: 'Volunteer', location: 'Nasirabad, Ctg', status: 'Verified' },
  { id: 13, name: 'Spice Garden', email: 'spice@rest.com', role: 'Restaurant', location: 'GEC, Ctg', status: 'Active' },
  { id: 14, name: 'Taj Restaurant', email: 'taj@rest.com', role: 'Restaurant', location: 'Bahaddarhat, Ctg', status: 'Active' },
  { id: 15, name: 'Ruchi Restaurant', email: 'ruchi@rest.com', role: 'Restaurant', location: 'Khulshi, Ctg', status: 'Pending' },
  { id: 16, name: 'Sultan\'s Dine', email: 'sultan@rest.com', role: 'Restaurant', location: 'Oxygen, Ctg', status: 'Active' },
  { id: 17, name: 'Chittagong Orphanage Trust', email: 'cot@ngo.org', role: 'NGO', location: 'Halishahar, Ctg', status: 'Verified' },
  { id: 18, name: 'Agrabad Women\'s Forum', email: 'awf@ngo.org', role: 'NGO', location: 'Agrabad, Ctg', status: 'Active' },
  { id: 19, name: 'Bayazid Food Bank', email: 'bayazid@ngo.org', role: 'NGO', location: 'Bayazid, Ctg', status: 'Verified' },
  { id: 20, name: 'Shah Amanat Foundation', email: 'saf@ngo.org', role: 'NGO', location: 'Shah Amanat, Ctg', status: 'Active' },
];

export const fetchDonations = () => [
  { id: 1, food: 'Chicken Dum Biriyani', qty: '30 kg', donor: 'Mezban Restaurant', date: '2026-08-05', status: 'Delivered' },
  { id: 2, food: 'Mutton Teheri', qty: '20 kg', donor: 'Bismillah Restaurant', date: '2026-08-05', status: 'Pending' },
  { id: 3, food: 'Pasta with White Sauce', qty: '15 kg', donor: 'Panshi Restaurant', date: '2026-08-04', status: 'Accepted' },
  { id: 4, food: 'Mutton Korma with Polao', qty: '22 kg', donor: 'Kasturi Garden', date: '2026-08-04', status: 'Delivered' },
  { id: 5, food: 'Vegetable Pizza', qty: '18 kg', donor: 'Alibaba Restaurant', date: '2026-08-03', status: 'Pending' },
  { id: 6, food: 'Chicken Meatbox', qty: '25 kg', donor: 'Handi Restaurant', date: '2026-08-03', status: 'Accepted' },
  { id: 7, food: 'Mutton Biriyani', qty: '35 kg', donor: 'The Peninsula', date: '2026-08-02', status: 'Delivered' },
  { id: 8, food: 'Chicken Fry with Fries', qty: '12 kg', donor: 'Spice Garden', date: '2026-08-02', status: 'Pending' },
  { id: 9, food: 'Chicken Curry with Rice', qty: '30 kg', donor: 'Taj Restaurant', date: '2026-08-01', status: 'Accepted' },
  { id: 10, food: 'Chicken Roast', qty: '16 kg', donor: 'Ruchi Restaurant', date: '2026-08-01', status: 'Delivered' },
  { id: 11, food: 'Vegetable Soup & Bread', qty: '18 kg', donor: 'Sultan\'s Dine', date: '2026-07-31', status: 'Pending' },
  { id: 12, food: 'Fish Curry with Rice', qty: '22 kg', donor: 'Mezban Restaurant', date: '2026-07-31', status: 'Accepted' },
  { id: 13, food: 'Mutton Chap', qty: '14 kg', donor: 'Bismillah Restaurant', date: '2026-07-30', status: 'Delivered' },
  { id: 14, food: 'Chicken Biriyani', qty: '28 kg', donor: 'Kasturi Garden', date: '2026-07-30', status: 'Accepted' },
  { id: 15, food: 'Plain Rice with Chicken Curry', qty: '40 kg', donor: 'Alibaba Restaurant', date: '2026-07-29', status: 'Pending' },
  { id: 16, food: 'Mutton Korma', qty: '18 kg', donor: 'Panshi Restaurant', date: '2026-07-29', status: 'Delivered' },
  { id: 17, food: 'Chicken Fries', qty: '10 kg', donor: 'Spice Garden', date: '2026-07-28', status: 'Accepted' },
  { id: 18, food: 'Chicken Bhuna with Rice', qty: '25 kg', donor: 'The Peninsula', date: '2026-07-28', status: 'Pending' },
  { id: 19, food: 'Mutton Polao', qty: '20 kg', donor: 'Taj Restaurant', date: '2026-07-27', status: 'Accepted' },
  { id: 20, food: 'Chicken Chap', qty: '14 kg', donor: 'Handi Restaurant', date: '2026-07-27', status: 'Delivered' },
  { id: 21, food: 'Chicken Tandoori', qty: '12 kg', donor: 'Mezban Restaurant', date: '2026-07-26', status: 'Pending' },
  { id: 22, food: 'Mutton Rezala', qty: '16 kg', donor: 'Bismillah Restaurant', date: '2026-07-26', status: 'Accepted' },
  { id: 23, food: 'Chicken Pasta', qty: '14 kg', donor: 'Panshi Restaurant', date: '2026-07-25', status: 'Delivered' },
  { id: 24, food: 'Vegetable Biriyani', qty: '20 kg', donor: 'Kasturi Garden', date: '2026-07-25', status: 'Pending' },
  { id: 25, food: 'Chicken Jhal Fry', qty: '10 kg', donor: 'Spice Garden', date: '2026-07-24', status: 'Accepted' },
];

export const fetchOrphanages = () => [
  { id: 1, name: 'Halishahar Children Home', food: 'Chicken Rice', qty: '25 kg', status: 'Pending' },
  { id: 2, name: 'Agrabad Orphanage', food: 'Mutton Korma', qty: '18 kg', status: 'Accepted' },
  { id: 3, name: 'Bakalia Orphanage', food: 'Pasta', qty: '15 kg', status: 'Pending' },
  { id: 4, name: 'Chandgaon Mission', food: 'Fish Rice', qty: '30 kg', status: 'Pending' },
  { id: 5, name: 'Pathantoly Children Home', food: 'Chicken Soup', qty: '12 kg', status: 'Accepted' },
  { id: 6, name: 'Nasirabad Boarding', food: 'Chicken Biriyani', qty: '22 kg', status: 'Pending' },
  { id: 7, name: 'Pahartali Orphanage', food: 'Mutton Teheri', qty: '16 kg', status: 'Accepted' },
  { id: 8, name: 'Khulshi Children Shelter', food: 'Pasta Sauce', qty: '14 kg', status: 'Pending' },
  { id: 9, name: 'GEC Orphanage', food: 'Chicken Roast', qty: '20 kg', status: 'Accepted' },
  { id: 10, name: 'Oxygen Orphanage', food: 'Chicken Curry', qty: '18 kg', status: 'Pending' },
  { id: 11, name: 'Bayazid Children Home', food: 'Mutton Korma', qty: '28 kg', status: 'Pending' },
  { id: 12, name: 'Shah Amanat Orphanage', food: 'Chicken Fry', qty: '15 kg', status: 'Accepted' },
  { id: 13, name: 'Ctg Club Foundation', food: 'Mutton Biriyani', qty: '20 kg', status: 'Pending' },
  { id: 14, name: 'Agrabad Women Shelter', food: 'Vegetable Rice', qty: '22 kg', status: 'Accepted' },
  { id: 15, name: 'Panchlaish Orphanage', food: 'Chicken Bhuna', qty: '25 kg', status: 'Pending' },
];

export const fetchFeedback = () => [
  { id: 1, from: 'Chittagong Food Bank', rating: 5, message: 'Excellent coordination, food was fresh and well-packed.', time: '1h ago' },
  { id: 2, from: 'Mezban Restaurant', rating: 4.8, message: 'Very easy donation process. Pickup was punctual.', time: '2h ago' },
  { id: 3, from: 'Suzana Akhter', rating: 5, message: 'Great platform! Helped us feed many children.', time: '3h ago' },
  { id: 4, from: 'Ibthesham Chowdhury', rating: 4.5, message: 'Smooth experience, but could improve notification system.', time: '4h ago' },
  { id: 5, from: 'Bismillah Restaurant', rating: 4.2, message: 'Good app, responsive admin team.', time: '5h ago' },
  { id: 6, from: 'Kasturi Garden', rating: 4.7, message: 'Very happy with the service. Will donate regularly.', time: '6h ago' },
  { id: 7, from: 'Green Hill NGO', rating: 5, message: 'Life-saving initiative! Highly recommended.', time: '7h ago' },
  { id: 8, from: 'Alibaba Restaurant', rating: 4.0, message: 'Could reduce pickup time, but overall good.', time: '8h ago' },
  { id: 9, from: 'Handi Restaurant', rating: 4.9, message: 'Outstanding support! Helped us during Eid.', time: '9h ago' },
  { id: 10, from: 'The Peninsula', rating: 4.3, message: 'Nice interface, easy to donate.', time: '10h ago' },
  { id: 11, from: 'Spice Garden', rating: 4.6, message: 'Great teamwork. Food reached orphans on time.', time: '11h ago' },
  { id: 12, from: 'Taj Restaurant', rating: 4.4, message: 'Very useful for surplus food management.', time: '12h ago' },
  { id: 13, from: 'Chittagong Orphanage Trust', rating: 5, message: 'We received fresh food daily. Thank you!', time: '1d ago' },
  { id: 14, from: 'Agrabad Women\'s Forum', rating: 4.8, message: 'Empowering community. Keep it up.', time: '1d ago' },
  { id: 15, from: 'Bayazid Food Bank', rating: 5, message: 'Smooth logistics, great communication.', time: '1d ago' },
  { id: 16, from: 'Sultan\'s Dine', rating: 4.2, message: 'Good app, but need more NGO participation.', time: '2d ago' },
  { id: 17, from: 'Ruchi Restaurant', rating: 4.0, message: 'Decent platform. Some delays in approval.', time: '2d ago' },
  { id: 18, from: 'Shah Amanat Foundation', rating: 5, message: 'Excellent service. Helped us feed 200+ children.', time: '2d ago' },
  { id: 19, from: 'Panshi Restaurant', rating: 4.5, message: 'Will recommend to other restaurants.', time: '3d ago' },
  { id: 20, from: 'Bonanza Restaurant', rating: 3.8, message: 'Pickup timing needs improvement.', time: '3d ago' },
];

export const fetchInventory = () => [
  { id: 1, name: 'Chicken Biriyani Special', qty: '40 kg', expiry: '2026-08-12' },
  { id: 2, name: 'Mutton Teheri Deluxe', qty: '25 kg', expiry: '2026-08-10' },
  { id: 3, name: 'Creamy Chicken Pasta', qty: '20 kg', expiry: '2026-08-09' },
  { id: 4, name: 'Mutton Korma Classic', qty: '28 kg', expiry: '2026-08-08' },
  { id: 5, name: 'Chicken Tandoori Special', qty: '18 kg', expiry: '2026-08-07' },
  { id: 6, name: 'Mutton Chap with Rice', qty: '20 kg', expiry: '2026-08-06' },
  { id: 7, name: 'Chicken Roast Special', qty: '22 kg', expiry: '2026-08-05' },
  { id: 8, name: 'Mutton Rezala Premium', qty: '24 kg', expiry: '2026-08-04' },
  { id: 9, name: 'Chicken Biriyani Royal', qty: '35 kg', expiry: '2026-08-03' },
  { id: 10, name: 'Mutton Polao Special', qty: '26 kg', expiry: '2026-08-02' },
  { id: 11, name: 'Spaghetti Bolognese', qty: '16 kg', expiry: '2026-08-20' },
  { id: 12, name: 'Chicken Alfredo Pasta', qty: '14 kg', expiry: '2026-08-19' },
  { id: 13, name: 'Crispy Chicken Fries', qty: '12 kg', expiry: '2026-08-18' },
  { id: 14, name: 'Mushroom Soup', qty: '10 kg', expiry: '2026-08-17' },
  { id: 15, name: 'Vegetable Fried Rice', qty: '18 kg', expiry: '2026-08-16' },
  { id: 16, name: 'Chicken Tikka Masala', qty: '20 kg', expiry: '2026-08-15' },
  { id: 17, name: 'Fish Fry with Lemon', qty: '15 kg', expiry: '2026-08-14' },
  { id: 18, name: 'Chicken Shawarma', qty: '12 kg', expiry: '2026-08-13' },
  { id: 19, name: 'Vegetable Pasta Bake', qty: '16 kg', expiry: '2026-08-12' },
  { id: 20, name: 'Chicken Noodle Soup', qty: '10 kg', expiry: '2026-08-11' },
  { id: 21, name: 'Grilled Chicken with Rice', qty: '22 kg', expiry: '2026-08-10' },
  { id: 22, name: 'Mutton Kebab', qty: '14 kg', expiry: '2026-08-09' },
  { id: 23, name: 'Pasta Salad', qty: '12 kg', expiry: '2026-08-08' },
  { id: 24, name: 'Chicken Stir Fry', qty: '16 kg', expiry: '2026-08-07' },
  { id: 25, name: 'Vegetable Curry with Rice', qty: '20 kg', expiry: '2026-08-06' },
];